Header header

#Total amount of available physical RAM [in kB] 
int32 memTotal

#Total amount of free RAM [in kB]
int32 memFree

#Amount of memory which is free but hold in a Buffer [in kB]
int32 memBuffers

#Amount of memory which is free and cached [in kB]
int32 memCached

#Total amount of available swap space (virtual RAM) [in kB]
int32 swapTotal

#Total free swap space [in kB]
int32 swapFree

#Amount of swap space which is free and cahed [in kB]
int32 swapCached
